<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.0.5</version>
        <relativePath/>
    </parent>

    <groupId>com.nlizzard</groupId>
    <artifactId>helloChat</artifactId>
    <version>1.0</version>
    <packaging>pom</packaging>

    <modules>
        <module>helloChat-common</module>
        <module>helloChat-pojo</module>
        <module>helloChat-api</module>
        <module>helloChat-gateway-1000</module>
        <module>helloChat-chat-875</module>
    </modules>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <!--spring cloud组件版本管理-->
        <spring.cloud.version>2025.1.1</spring.cloud.version>
        <spring.cloud.alibaba.version>2025.1.0.0</spring.cloud.alibaba.version>
        <!--mybatis-plus 版本管理-->
        <mybatis-plus.version>3.5.16</mybatis-plus.version>
        <!--minio版本管理-->
        <minio.version>8.4.5</minio.version>
        <okhttp.version>4.8.1</okhttp.version>
        <!--工具类版本管理-->
        <commons.codec.version>1.15</commons.codec.version>
        <commons.lang3.version>3.12.0</commons.lang3.version>
        <commons.fileupload.version>1.6.0</commons.fileupload.version>
        <commons.io.version>2.14.0</commons.io.version>
        <!-- 二维码生成工具版本管理-->
        <zxing.version>3.5.4</zxing.version>
        <!--netty版本管理-->
        <netty.version>4.2.12.Final</netty.version>
    </properties>


    <dependencyManagement>
        <dependencies>
            <!--引入spring cloud-->
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring.cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!--引入spring cloud Alibaba 依赖-->
            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>${spring.cloud.alibaba.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>


            <!-- mybatis-plus 相关依赖 -->
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-spring-boot4-starter</artifactId>
                <version>${mybatis-plus.version}</version>
            </dependency>

            <!-- minio相关依赖 -->
            <dependency>
                <groupId>io.minio</groupId>
                <artifactId>minio</artifactId>
                <version>${minio.version}</version>
            </dependency>

            <dependency>
                <groupId>com.squareup.okhttp3</groupId>
                <artifactId>okhttp</artifactId>
                <version>${okhttp.version}</version>
            </dependency>

            <!-- 二维码生成依赖 -->
            <dependency>
                <groupId>com.google.zxing</groupId>
                <artifactId>core</artifactId>
                <version>${zxing.version}</version>
            </dependency>

            <!--引入apache 通用工具类-->
            <dependency>
                <groupId>commons-codec</groupId>
                <artifactId>commons-codec</artifactId>
                <version>${commons.codec.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-lang3</artifactId>
                <version>${commons.lang3.version}</version>
            </dependency>
            <dependency>
                <groupId>commons-fileupload</groupId>
                <artifactId>commons-fileupload</artifactId>
                <version>${commons.fileupload.version}</version>
            </dependency>
            <dependency>
                <groupId>commons-io</groupId>
                <artifactId>commons-io</artifactId>
                <version>${commons.io.version}</version>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-all</artifactId>
                <version>${netty.version}</version>
                <scope>compile</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>