server:
  port: 1000

spring:
  profiles:
    active: dev
  application:
    name: gateway-service
  # redis配置
  data:
    redis:
      database: ${redis.database}
      host: ${redis.host}
      port: ${redis.port}
      password: ${redis.password}
  config:
    import:
      - nacos:gateway-dev.yaml?group=DEFAULT_GROUP
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
      # 服务注册/发现
      discovery:
        server-addr: ${nacos.discovery.addr}
        username: ${nacos.discovery.username}
        password: ${nacos.discovery.password}
      # 配置管理
      server-addr: 192.168.123.2:18848
      username: nacos
      password: nacos
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: authRoute
              uri: lb://auth-service
              predicates:
                - Path=/auth/**,/passport/**
            - id: fileRoute
              uri: lb://file-service
              predicates:
                - Path=/file/**,/static/**
            - id: mainRoute
              uri: lb://main-service
              predicates:
                - Path=/main/**,/userInfo/**
          globalcors:
            cors-configurations:
              '[/**]':
                allow-credentials: true
                allowed-headers: "*"
                allowed-origin-patterns: "*"
                allowed-methods: "*"
#blackIp:
#  continueCounts: 5  #操作次数限制
#  timeInterval: 20   #操作间隔限制 （单位：秒）
#  limitTimes: 30     #限制访问时长 （单位：秒）

# 日志级别
logging:
  level:
    root: info