exclude.urls[0]=/passport/getSMSCode
exclude.urls[1]=/passport/registry
exclude.urls[2]=/passport/login
exclude.urls[3]=/passport/registryOrLogin
exclude.urls[4]=/friendship/isBlack
exclude.urls[5]=/chat/getNettyOnlineInfo
# 放行静态资源路径
exclude.fileStart=/static/**
